### ISSUE TITLE
One of the candidates was not elected from top 5 votes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3613]
## Scope
* [ ] Review the underlying problem and try to fix it if it lies on Pioneer side
* [ ] Raise a corresponding runtime bug if its not

## Context
Reported here: https://discord.com/channels/811216481340751934/812345044094156811/1020232217261252608

Problem: 

Votes not reflected in the App

![Screenshot 2022-09-16 at 11.48.54.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/ea61c24c-9b0f-4143-81bf-8c5d3138afb6)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203239352981898) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
@dmtrjsg this was already a known issue and the solution was coded and put into carthage relase: https://github.com/Joystream/joystream/issues/3530

**Comment by thesan** [comment]
The runtime was fixed here: https://github.com/Joystream/joystream/pull/3797

But Pioneer should also order the candidates by voting power first then by votes number second, in the revealing stage and the past elections

**Comment by ivanturlakov** [comment]
@dmtrjsg In terms of testing, this seems to be the same situation as the #2715? (testing env is set up with one council seat)

**Comment by dmtrjsg** [comment]
ok will ask to spin up a network with 3 council seats, thank you for raising the comment!

**Comment by dmtrjsg** [comment]
@ivanturlakov there we go buddy: https://54.227.116.57.nip.io/newtork/config

**Comment by ivanturlakov** [comment]
@dmtrjsg there is a blocker https://github.com/Joystream/pioneer/issues/3609#issuecomment-1268282935

**Comment by dmtrjsg** [comment]
@ivanturlakov but I think the 3609 only addresses auto-refetch, but you can do it with page refresh (or wait for a few mins for QN to catchup), or is this a real blocker?

**Comment by ivanturlakov** [comment]
@dmtrjsg When I press the vote button, the spinner appears and is visible for a few minutes, the voting window does not open
<img width="1188" alt="Снимок экрана 2022-10-10 в 17 24 06" src="https://user-images.githubusercontent.com/46903215/194889715-0cb4f2f7-5ec7-4fd6-9961-4fa660761124.png">
<img width="1185" alt="Снимок экрана 2022-10-10 в 17 26 10" src="https://user-images.githubusercontent.com/46903215/194889706-5fbc6884-0e8c-4fc7-8a40-234c02fb4802.png">

**Comment by dmtrjsg** [comment]
Probably same issue as in 
#3609

**Comment by dmtrjsg** [comment]
This is already fixed in the connected PR (when candidates drop out of the leaderboard (top 5) and get voted back in). 

https://gist.github.com/thesan/f57705e850a0a79001f46e1044ceb626
The key transaction is: adovrn +32,000,000 where ferdikesh_studio gets to the 6th position thus looses 7,600,000 which is more than the difference between his final voting power: 36,675,000 and isonar's 35,000,000
It also happens to adovrn earlier but he only lost 10,000 and ismail who loses 120,000

**Comment by dmtrjsg** [comment]
Confirmed this case was due to the bug that was already fixed. 

To be tested by @bwhm as part of last round of Cartrhage testing.

**Comment by ivanturlakov** [comment]
@dmtrjsg @traumschule

Tested on https://dao-git-carthage-joystream.vercel.app/#/election
wss://54.227.116.57.nip.io/ws-rpc

3 council seats

### Candidates

<img width="1179" alt="Снимок экрана 2022-10-29 в 14 24 27" src="https://user-images.githubusercontent.com/46903215/198828964-107f9084-cf3f-4b8e-ab87-60f61ad55026.png">

### Alice voted 55,000 for herself
<img width="1179" alt="Снимок экрана 2022-10-29 в 14 40 50" src="https://user-images.githubusercontent.com/46903215/198829454-c9adeb25-b0db-4feb-9868-0ae71c62b8a8.png">

### Next, different members voted for each candidate 5,000

### Total votes:
Alice 55 000 + 5000 = 60 000
Candidate 2 - 5000
Candidate 3 - 5000
Candidate 4 - 5000

### Votes revealed

⚠️ Alice "My stake" field updated to 55 000 after the page reload

<img width="1187" alt="Снимок экрана 2022-10-29 в 14 23 26" src="https://user-images.githubusercontent.com/46903215/198828959-4645c29e-9655-4cff-9f35-a19f57e545fe.png">
<img width="904" alt="Снимок экрана 2022-10-29 в 14 26 49" src="https://user-images.githubusercontent.com/46903215/198828961-725a50b8-1426-4630-8e1b-c1f7dbea58a7.png">

**Comment by traumschule** [comment]
Thanks! For this one we need to reproduce a case that failed on Rhodes in same voting and revealing order. @dmtrjsg or can we skip this because it was tested pro grammatically?

out of scope:
- Was the `55 000 after the page reload` fixed automatically or did you have reload?
- My Stake: #2985
- Sounds like you didn't experience #2986 and it can be closed?

**Comment by ivanturlakov** [comment]
>Alice "My stake" field updated to 55 000 after the page reload
>Was the 55 000 after the page reload fixed automatically or did you have reload?

I checked it again. The update to 55,000 only happens after the revealing period is over. During the revealing period, this field shows 60,000, even if I refresh the page

.

>Sounds like you didn't experience 2986 and it can be closed?

No, it's still happening

**Comment by dmtrjsg** [comment]
@traumschule  I think this requires manual testing and would be good to test the exact order of revealing 👍

Just a refresher on the scenario to test: 

  // This is how the referendum goes:
    // 1. Candidate 1 gets a vote = 100
    // 2. Candidate 2 gets a vote = 50
    // 3. Candidate 3 gets a vote = 30
    // 4. Candidate 3 gets a vote = 30
    // 5. Candidate 3 gets a vote = 30
    // 6. Votes from 1-5 are revealed one after another
    // Expected outcome: winners are Candidate 1 (100), Candidate 3 (90)
    // Actual outcome: winners are Candidate 1 (100), Candidate 2 (50)

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/election
wss://54.227.116.57.nip.io/ws-rpc

@dmtrjsg @traumschule 
I had to tweak the scenario a bit to fit the parameters of the env(3 council seats; 300 - min vote):

// This is how the referendum goes:
// 0. Candidate a gets a vote = 1500
// 1. Candidate 1 gets a vote = 1000
// 2. Candidate 2 gets a vote = 500
// 3. Candidate 3 gets a vote = 300
// 4. Candidate 3 gets a vote = 300
// 5. Candidate 3 gets a vote = 300
// 6. Votes from 1-6 are revealed one after another
✅ // Expected outcome: winners are Candidate a (1500), Candidate 1 (1000), Candidate 3 (900)
// Actual outcome: winners are Candidate a (1500), Candidate 1 (1000), Candidate 2 (500)

<img width="1195" alt="Снимок экрана 2022-10-31 в 16 38 38" src="https://user-images.githubusercontent.com/46903215/199037028-86380bfa-2096-4d77-8717-b8b23224eb2c.png">
<img width="1189" alt="Снимок экрана 2022-10-31 в 16 41 26" src="https://user-images.githubusercontent.com/46903215/199037030-bfd03575-ceeb-4412-b20f-e461b790e758.png">
<img width="906" alt="Снимок экрана 2022-10-31 в 16 41 44" src="https://user-images.githubusercontent.com/46903215/199037032-2d71e703-f2f5-4306-bb19-dc67db00deb2.png">
